version: 0.0

os: linux

files:
  - source: /gs-maven-0.1.0.jar
    destination: /tmp

hooks:
#   ApplicationStop:
#     - location: stop-process.sh
#       timeout: 180
#       runas: root
  ApplicationStart:
    - location: start-process.sh
      timeout: 180
      runas: root


