version: 0.2
env:
  variables:
    git_url: "git@github.com:Ecolane/hello-world-maven-project.git"
  parameter-store:
    ssh_key: k3-pipeline-rsa
    ssh_pub: k3-pipeline-rsa.pub
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      #- mvn clean install
      - VERSION=1.0.0
      - mkdir -p ~/.ssh
      - echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE/BtQkl7K/4X9Hfy+ck3z/+WCBhvxxiFf2k7DK4Rm5y pipelinetesting" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - eval $(ssh-agent -s ) &&  ssh-add ~/.ssh/id_rsa
      #- ssh-keygen -F github.com || ssh-keyscan github.com >>~/.ssh/known_hosts
      - git config --global url."git@github.com:".insteadOf "https://github.com/"
  post_build:
    commands:
      - echo Build completed on `date`
      - cd $CODEBUILD_SRC_DIR
      - sed -ie "s/5.X.X/$VERSION/g" ansibelfile
      - mkdir -p roles/drt_updater_part1/tasks/
      - touch roles/drt_updater_part1/tasks/$VERSION
      - mv $CODEBUILD_SRC_DIR/ansiblefile roles/drt_updater_part1/tasks/$VERSION
      - ls -lrt roles/drt_updater_part1/tasks/$VERSION
      - git add .
      - git commit -m "FF"
      - git push origin main
#artifacts:
 # files:
  #  - target/gs-maven-0.1.0.jar
   # - appspec.yml
    #- scripts/start-process.sh
    #- scripts/stop-process.sh
    #- '**/*'
  #discard-paths: yes
