version: 0.2
env:
  variables:
    git_url: "git@github.com:Ecolane/hello-world-maven-project.git"
  parameter-store:
    ssh_key: k3-pipeline-rsa
    ssh_pub: k3-pipeline-rsa-pub
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ls -lrt
      - cat ansiblefile
      ##- mvn clean install
      - VERSION=1.0.9
      - mkdir -p /root/.ssh
      - cp testing_rsa /root/.ssh/id_rsa
      - cp testing_rsa.pub /root/.ssh/id_rsa.pub
      - chmod 600 /root/.ssh/id_rsa
      - eval $(ssh-agent -s)
      - ssh-add /root/.ssh/id_rsa
      - ssh-keygen -F github.com || ssh-keyscan github.com >>~/.ssh/known_hosts
      - git config --global url."git@github.com:".insteadOf "https://github.com/"
      - mkdir -p roles/drt_updater_part1/tasks/
      - touch roles/drt_updater_part1/tasks/$VERSION
      - cp ansiblefile ansiblefile1
      - sed -i "s/5.X.X.X/$VERSION/g" ansiblefile1
      - sed -i "s/5.X.X/$VERSION/g" ansiblefile1
      #- mv $CODEBUILD_SRC_DIR/ansiblefile1 $CODEBUILD_SRC_DIR_ansible/roles/drt_updater_part1/tasks/$VERSION
      #- ls -lrt roles/drt_updater_part1/tasks/$VERSION
      #- cat roles/drt_updater_part1/tasks/$VERSION
      - pwd      
  post_build:
    commands:
      - echo Build completed on `date`
      - cd $CODEBUILD_SRC_DIR_ansible
      - ls -lrta *
      - tar -cvzf ansible.tar.gz $CODEBUILD_SRC_DIR_ansible
      #- git checkout DevOps-PipeLine
      #- mv $CODEBUILD_SRC_DIR/ansiblefile1 $CODEBUILD_SRC_DIR_ansible/roles/drt_updater_part1/tasks/$VERSION
      #- ls -lrt roles/drt_updater_part1/tasks/$VERSION
      #- ls -lrt $CODEBUILD_SRC_DIR_ansible/roles/drt_updater_part1/tasks/$VERSION
      #- cat roles/drt_updater_part1/tasks/$VERSION
      #- pwd 
      #- git remote set-url origin git@github.com:Ecolane/ansible.git
      #- git config --global user.email "systems@ecolane.com"
     #- git config --global user.name "awscodebuild"
      #- git status
      #- git add roles/drt_updater_part1/tasks/.
      #- git commit -m "creating new version"
     ### - git branch -a
     # - git push origin DevOps-PipeLine
      #- git submodule init
     # - git submodule update --recursive
artifacts:
  files:
  #  - target/gs-maven-0.1.0.jar
   # - appspec.yml
    #- scripts/start-process.sh
    #- scripts/stop-process.sh
    #- '**/*'
    - ansible.tar.gz
  #discard-paths: yes
