version: 0.2
#env:
 # variables:
  ##  git_url: "git@github.com:Ecolane/hello-world-maven-project.git"
  #parameter-store:
  #  ssh_key: k3-pipeline-rsa
   # ssh_pub: k3-pipeline-rsa.pub
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - ls -lrt
      - echo Build started on `date`
      - cp ansiblefile ansiblefile1
      - sed -ie "s/5.X.X.X/$VERSION/g" ansiblefile
      - sed -ie "s/5.X.X/$VERSION/g" ansiblefile
      - ls -lrt
      - cat ansiblefile
      #- mvn clean install
      - VERSION=1.0.0
      - mkdir -p /root/.ssh
      - cp testing_rsa /root/.ssh/id_rsa
      - cp testing_rsa.pub /root/.ssh/id_rsa.pub
      - chmod 600 /root/.ssh/id_rsa
      - eval $(ssh-agent -s)
      - ssh-add /root/.ssh/id_rsa
      # &&  ssh-add /root/.ssh/id_rsa
      #- ssh -T git@github.com
      - ssh-keygen -F github.com || ssh-keyscan github.com >>~/.ssh/known_hosts
      - git config --global url."git@github.com:".insteadOf "https://github.com/"
      - git submodule init
      - git submodule update --recursive
  post_build:
    commands:
      - echo Build completed on `date`
      - cd $CODEBUILD_SRC_DIR
      - git checkout main
      - git remote set-url origin git@github.com:Ecolane/hello-world-maven-project.git
      - git config --global user.email "systems@ecolane.com"
      - git config --global user.name "awscodebuild"
      - mkdir -p roles/drt_updater_part1/tasks/
      - touch roles/drt_updater_part1/tasks/$VERSION
      - mv $CODEBUILD_SRC_DIR/ansiblefile roles/drt_updater_part1/tasks/$VERSION
      - ls -lrt roles/drt_updater_part1/tasks/$VERSION
      - ls -lrt .git/config
      - cat .git/config
      - git add .
      - git commit -m "FF"
      - git branch -a
      - git push origin main
#artifacts:
 # files:
  #  - target/gs-maven-0.1.0.jar
   # - appspec.yml
    #- scripts/start-process.sh
    #- scripts/stop-process.sh
    #- '**/*'
  #discard-paths: yes
