version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - echo Testing
  build:
    commands:
      - echo Build started on `date`
      - printenv
      - echo $CODEBUILD_WEBHOOK_PREV_COMMIT
      - echo "Testing"
      #- aws codepipeline start-pipeline-execution --name Demo-Testing
     # - |
     # # if 